#!/bin/sh
# Bump the version number and create a commit with the updated version
# TODO: Doesn't work with numbers larger than 9 (e.g. 1.10.1)

# Read current version from iso_version variable
CURR_SEM_VER="$(cat profiledef.sh | grep 'iso_version' | cut -d'=' -f2)"
CURR_LAB_VER="$(cat profiledef.sh | grep 'iso_label' | cut -d'=' -f2)"

# Remove extra text from version numbers
CURR_SEM_VER="$(echo ${CURR_SEM_VER} | sed s/\"//g)"
CURR_LAB_VER="$(echo ${CURR_LAB_VER} | sed s/GDL-// | sed s/\"//g)"

[ $# -ne 1 ] && echo "Usage: $0 [VERSION] (e.g. 'bump 1.3.0')" && exit 1

NEW_SEM_VER="$1"

# Remove all dots (.) from version number
NEW_LAB_VER="$(echo ${NEW_SEM_VER} | sed s/\\.//g)"

# Update version numbers in profiledef.sh
sed -i.bak\
    -e "s/iso_label=\"GDL-${CURR_LAB_VER}\"/iso_label=\"GDL-${NEW_LAB_VER}\"/" \
    -e "s/iso_version=\"${CURR_SEM_VER}\"/iso_version=\"${NEW_SEM_VER}\"/" \
    profiledef.sh

echo "Bumped version number to ${NEW_SEM_VER}."
echo "Saved backup to 'profiledef.sh.bak', you can delete if you want."
