#!/bin/bash
#
# This script will run once, at user's first login, then self-destruct.

set_initial_gsettings() {
  # gnome desktop
  gsettings set org.gnome.desktop.background picture-uri 'file:///usr/share/backgrounds/gds-logo-dark-3840x2160.jpg'
  gsettings set org.gnome.desktop.input-sources xkb-options "['numpad:microsoft']"
  gsettings set org.gnome.desktop.interface clock-format '12h'
  gsettings set org.gnome.desktop.interface clock-show-weekday true
  gsettings set org.gnome.desktop.interface cursor-theme 'Breeze_Amber'
  gsettings set org.gnome.desktop.interface gtk-theme 'Matcha-dark-aliz'
  gsettings set org.gnome.desktop.interface icon-theme 'Surfn-Numix'
  gsettings set org.gnome.desktop.interface show-battery-percentage true
  gsettings set org.gnome.desktop.notifications show-in-lock-screen false
  gsettings set org.gnome.desktop.peripherals.mouse speed 1.0
  gsettings set org.gnome.desktop.privacy remember-recent-files false
  gsettings set org.gnome.desktop.screensaver picture-uri 'file:///usr/share/backgrounds/gds-drake-dark-3840x2160.jpg'
  gsettings set org.gnome.desktop.session idle-delay 'uint32 600'
  gsettings set org.gnome.desktop.wm.keybindings panel-run-dialog "['<Super>r']"
  gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"
  gsettings set org.gnome.desktop.wm.preferences action-middle-click-titlebar 'minimize'
  gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'

  # gnome shell
  gsettings set org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com', 'workspace-indicator@gnome-shell-extensions.gcampax.github.com', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'clipboard-indicator@tudmotu.com']"
  gsettings set org.gnome.shell.extensions.user-theme name 'Matcha-dark-aliz'
  gsettings set org.gnome.shell.keybindings toggle-overview '@as []'

  # plugins
  gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
  gsettings set org.gnome.settings-daemon.plugins.media-keys calculator "['<Super>c']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys control-center "['<Super>s']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys home "['<Super>f']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys www "['<Super>w']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Super>e'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command 'gedit'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'Open text editor'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding '<Super>t'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command 'terminator'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name 'Open terminator'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ binding '<Primary><Alt>t'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ command 'terminator'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ name 'Open terminator'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ binding '<Shift><Super>c'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ command 'gnome-characters'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ name 'Open GNOME Characters'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ binding "['<Shift><Super>t', '<Primary><Shift><Alt>t']"
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ command 'cool-retro-term --fullscreen'
  gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ name 'Open Cool Retro Terminal'
  gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-timeout 7200

  # mutter
  gsettings set org.gnome.mutter attach-modal-dialogs false

  # nautilus
  gsettings set org.gnome.nautilus.icon-view captions "['size', 'none', 'none']"
  gsettings set org.gnome.nautilus.list-view use-tree-view true
  gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
  gsettings set org.gnome.nautilus.preferences show-delete-permanently true
  gsettings set org.gnome.nautilus.preferences thumbnail-limit 'uint64 100'

  # gedit
  gsettings set org.gnome.gedit.plugins active-plugins "['spell', 'sort', 'docinfo', 'filebrowser', 'modelines', 'quickhighlight']"
  gsettings set org.gnome.gedit.preferences.editor display-right-margin true
  gsettings set org.gnome.gedit.preferences.editor insert-spaces true
  gsettings set org.gnome.gedit.preferences.editor scheme 'Adwaita-dark'
  gsettings set org.gnome.gedit.preferences.editor tabs-size 'uint32 2'
  gsettings set org.gnome.gedit.preferences.editor wrap-last-split-mode 'word'

  # file-chooser
  gsettings set org.gtk.Settings.FileChooser clock-format '12h'
  gsettings set org.gtk.Settings.FileChooser sort-directories-first true
}

# run twice to ensure the ordering of gsettings commands isn't an issue
set_initial_gsettings
set_initial_gsettings

# cleanup
rm ~/.config/autostart/set-initial-gsettings.desktop
rm ~/.config/set-initial-gsettings
