#!/usr/bin/env bash

fs_select() {
  if "${VFAT}"; then
    FS=$(dialog --stdout --menu "${vfat_msg}" 11 65 1 "vfat" "${fs7}")
    if [ "$?" -gt "0" ]; then
      part_menu
    fi
    VFAT=false
  else
    if [ "${f2fs}" -eq "0" ]; then
      FS=$(dialog --stdout --nocancel --menu "${fs_msg}" 17 65 8 \
        "ext4" "${fs0}" \
        "ext3" "${fs1}" \
        "ext2" "${fs2}" \
        "btrfs" "${fs3}" \
        "f2fs" "${fs6}" \
        "jfs" "${fs4}" \
        "reiserfs" "${fs5}" \
        "xfs" "${fs8}")
    elif "${BTRFS}"; then
      FS=$(dialog --stdout --nocancel --menu "${fs_msg}" 16 65 7 \
        "ext4" "${fs0}" \
        "ext3" "${fs1}" \
        "ext2" "${fs2}" \
        "btrfs" "${fs3}" \
        "jfs" "${fs4}" \
        "reiserfs" "${fs5}" \
        "xfs" "${fs8}")
    else
      FS=$(dialog --stdout --nocancel --menu "${fs_msg}" 15 65 6 \
        "ext4" "${fs0}" \
        "ext3" "${fs1}" \
        "ext2" "${fs2}" \
        "jfs" "${fs4}" \
        "reiserfs" "${fs5}" \
        "xfs" "${fs8}")
      BTRFS=true
    fi
  fi

  if [ "${FS}" = "f2fs" ]; then
    ENABLE_F2FS=true
  elif [ "${FS}" = "btrfs" ]; then
    ENABLE_BTRFS=true
  elif [ "${FS}" = "xfs" ]; then
    enable_xfs=true
  fi
}
