#!/usr/bin/env bash

graphics() {
  op_title="${de_op_msg}"
  while (true); do
    de=$(dialog --ok-button "${done_msg}" --cancel-button "${cancel}" --menu "${environment_msg}" 15 60 5 \
      "gdl-gnome" "${de0}" \
      "gdl-cinnamon" "${de1}" \
      "gdl-xfce" "${de2}" 3>&1 1>&2 2>&3)
    if [ -n "${de}" ]; then
      break
    fi
  done

  source "${lang_file}"

  while read -r env; do
    case "${env}" in
    "gdl-gnome")
      config_env="${env}"
      start_term="exec gnome-session"
      DE+="gnome gnome-extra terminator ${extras} "
      ;;
    "gdl-cinnamon")
      config_env="${env}"
      DE+="cinnamon cinnamon-translations gnome-screenshot gnome-terminal file-roller p7zip zip unrar terminator ${extras} "
      start_term="exec cinnamon-session"
      ;;
    "gdl-xfce")
      config_env="${env}"
      start_term="exec startxfce4"
      DE+="xfce4 xfce4-goodies file-roller p7zip zip unrar ${extras} "
      ;;
    esac
  done <<<"${de}"

  while (true); do
    if "${VM}"; then
      case "${virt}" in
      qemu) GPU="spice-vdagent " ;;
      vbox)
        msg "\n${vbox_msg}"
        GPU="virtualbox-guest-utils virtualbox-guest-dkms "
        ;;
      vmware)
        msg "\n${vmware_msg}"
        GPU="xf86-video-vmware xf86-input-vmmouse open-vm-tools net-tools gtkmm mesa mesa-libgl"
        ;;
      hyper-v)
        msg "\n${hyperv_msg}"
        GPU="xf86-video-fbdev mesa-libgl"
        ;;
      *)
        msg "\n${vm_msg}"
        GPU="xf86-video-fbdev mesa-libgl"
        ;;
      esac
      break
    fi

    if "${NVIDIA}"; then
      GPU=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" --menu "${graphics_msg}" 18 60 6 \
        "${default}" "${gr0}" \
        "xf86-video-ati" "${gr4}" \
        "xf86-video-amdgpu" "${gr10}" \
        "xf86-video-intel" "${gr5}" \
        "xf86-video-nouveau" "${gr8}" \
        "xf86-video-vesa" "${gr1}" \
        "NVIDIA" "${gr2} ->" 3>&1 1>&2 2>&3)
      ex="$?"
    else
      GPU=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" --menu "${graphics_msg}" 17 60 5 \
        "${default}" "${gr0}" \
        "xf86-video-ati" "${gr4}" \
        "xf86-video-amdgpu" "${gr10}" \
        "xf86-video-intel" "${gr5}" \
        "xf86-video-nouveau" "${gr8}" \
        "xf86-video-vesa" "${gr1}" 3>&1 1>&2 2>&3)
      ex="$?"
    fi

    if [ "${GPU}" == "NVIDIA" ]; then
      GPU=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" --menu "${nvidia_msg}" 15 60 4 \
        "${gr0}" "->" \
        "nvidia" "${gr6}" \
        "nvidia-390xx" "${gr9}" \
        "nvidia-340xx" "${gr7}" 3>&1 1>&2 2>&3)

      if [ "$?" -eq "0" ]; then
        if [ "${GPU}" == "${gr0}" ]; then
          pci_id=$(lspci -nn | grep "VGA" | egrep -o '\[.*\]' | awk '{print $NF}' | sed 's/.*://;s/]//')
          if (grep <"${gdl_directory}"/etc/nvidia390.xx "${pci_id}" &>/dev/null); then
            if (yesno "\n${nvidia_390msg}" "${yes}" "${no}"); then
              if [ "${kernel}" == "lts" ]; then
                GPU="nvidia-390xx-lts"
              else
                GPU="nvidia-390xx"
              fi
              GPU+=" nvidia-390xx-libgl nvidia-390xx-utils nvidia-settings"
              break
            fi
          elif (grep <"${gdl_directory}"/etc/nvidia340.xx "${pci_id}" &>/dev/null); then
            if (yesno "\n${nvidia_340msg}" "${yes}" "${no}"); then
              if [ "${kernel}" == "lts" ]; then
                GPU="nvidia-340xx-lts"
              else
                GPU="nvidia-340xx"
              fi
              GPU+=" nvidia-340xx-libgl nvidia-340xx-utils nvidia-settings"
              break
            fi
          elif (yesno "\n${nvidia_curmsg}" "${yes}" "${no}"); then
            if [ "${kernel}" == "lts" ]; then
              GPU="nvidia-lts"
            else
              GPU="nvidia"
            fi

            if (yesno "\n${nvidia_modeset_msg}" "${yes}" "${no}"); then
              drm=true
            fi
            GPU+=" nvidia-libgl nvidia-utils nvidia-settings"
            break
          fi
        elif [ "${GPU}" == "nvidia" ]; then
          if (yesno "\n${nvidia_modeset_msg}" "${yes}" "${no}"); then
            drm=true
          fi

          if [ "${kernel}" == "lts" ]; then
            GPU="nvidia-lts nvidia-libgl nvidia-utils nvidia-settings"
          else
            GPU+=" ${GPU}-libgl ${GPU}-utils"
          fi
          break
        else
          if [ "${kernel}" == "lts" ]; then
            GPU="${GPU}-lts ${GPU}-libgl ${GPU}-utils"
          else
            GPU+=" ${GPU}-libgl ${GPU}-utils"
          fi
          break
        fi
      fi
    elif [ "${GPU}" == "${default}" ]; then
      GPU="${default_GPU} mesa-libgl"
      break
    else
      GPU+=" mesa-libgl"
      break
    fi
  done

  DE+="${GPU} ${de_defaults} "

  if [ "${net_util}" == "networkmanager" ]; then
    if (grep <<<"${DE}" "plasma" &>/dev/null); then
      DE+="plasma-nm "
    else
      DE+="network-manager-applet "
    fi
  fi

  if (yesno "\n${touchpad_msg}" "${yes}" "${no}"); then
    if (grep <<<"${DE}" "gnome" &>/dev/null); then
      DE+="xf86-input-libinput "
    else
      DE+="xf86-input-synaptics "
    fi
  fi

  if "${enable_bt}"; then
    if (yesno "\n${blueman_msg}" "${yes}" "${no}"); then
      DE+="blueman "
    fi
  fi

  if (yesno "\n${dm_msg}" "${yes}" "${no}"); then
    DM=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" --menu "${dm_msg1}" 13 64 4 \
      "lightdm" "${dm1}" \
      "gdm" "${dm0}" \
      "lxdm" "${dm2}" \
      "sddm" "${dm3}" 3>&1 1>&2 2>&3)
    if [ "$?" -eq "0" ]; then
      if [ "${DM}" == "lightdm" ]; then
        DE+="$DM lightdm-gtk-greeter lightdm-gtk-greeter-settings "
      elif [ "${DM}" == "lxdm" ] && "$GTK3"; then
        DE+="${DM}-gtk3 "
      else
        DE+="$DM "
      fi
      enable_dm=true
    else
      msg "\n${startx_msg}"
    fi
  else
    msg "\n${startx_msg}"
  fi

  base_install+="${DE} "
  desktop=true
}

config_env() {
  arch-chroot "${ARCH}" fc-cache -f
  cp "${gdl_directory}"/extra/gdl-icon.png "${ARCH}"/root/.face
  cp "${gdl_directory}"/extra/gdl-icon.png "${ARCH}"/etc/skel/.face
  cp "${gdl_directory}"/extra/gdl-icon.png "${ARCH}"/usr/share/pixmaps
  mkdir "${ARCH}"/usr/share/backgrounds/gdl
  cp -r "${gdl_directory}"/extra/wallpapers/* "${ARCH}"/usr/share/backgrounds/gdl/

  if [ -n "${config_env}" ]; then
    cp -R "${gdl_directory}/extra/desktop/${config_env}/*" -t "${ARCH}"/root
    cp -R "${gdl_directory}/extra/desktop/${config_env}/.config" -t "${ARCH}"/etc/skel

  fi

  case "${config_env}" in
  "gdl-gnome")
    cp -r "${gdl_directory}/extra/desktop/gdl-gnome/gnome-backgrounds.xml" "${ARCH}"/usr/share/gnome-background-properties
    ;;
  esac

  log "Configured: ${config_env}"
}
