#!/bin/bash

set_locale() {
  op_title="${locale_op_msg}"
  while (true); do
    LOCALE="$(dialog --stdout --no-cancel --ok-button "${ok}" \
      --menu "\n${locale_msg}" 18 60 11 \
      "de_DE.UTF-8" "German" \
      "el_GR.UTF-8" "Greek" \
      "en_AU.UTF-8" "English (Australia)" \
      "en_CA.UTF-8" "English (Canada)" \
      "en_GB.UTF-8" "English (UK)" \
      "en_US.UTF-8" "English (US)" \
      "es_ES.UTF-8" "Spanish (Spain)" \
      "es_MX.UTF-8" "Spanish (Mexico)" \
      "fr_FR.UTF-8" "French" \
      "hu_HU.UTF-8" "Hungarian" \
      "it_IT.UTF-8" "Italian" \
      "lv_LV.UTF-8" "Latvian" \
      "pt_BR.UTF-8" "Portuguese (Brazil)" \
      "pt_PT.UTF-8" "Portuguese (Portugal)" \
      "ro_RO.UTF-8" "Romanian" \
      "ru_RU.UTF-8" "Russian" \
      "sv_SE.UTF-8" "Swedish" \
      "${other}" "${other}-locale")"
    if [ "${LOCALE}" = "${other}" ]; then
      LOCALE="$(dialog --stdout --ok-button "${ok}" --cancel-button "${cancel}"\
        --menu "\n${locale_msg}" 18 60 11 ${localelist})"
      if [ "$?" -eq "0" ]; then
        break
      fi
    else
      break
    fi
  done
  log "Set locale to: ${LOCALE}"
}

set_zone() {
  op_title="${zone_op_msg}"
  while (true); do
    ZONE="$(dialog --stdout --no-cancel --ok-button "${ok}" \
      --menu "\n${zone_msg0}" 18 60 11 ${zonelist})"
    if (find /usr/share/zoneinfo -maxdepth 1 -type d | sed -n -e 's!^.*/!!p' |
        grep "${ZONE}" &>/dev/null); then
      sublist="$(find /usr/share/zoneinfo/"${ZONE}" -maxdepth 1 |
        sed -n -e 's!^.*/!!p' | sort | sed 's/$/ -/g' | grep -v "${ZONE}")"
      SUBZONE="$(dialog --stdout --ok-button "${ok}" --cancel-button "${back}" \
        --menu "\n${zone_msg1}" 18 60 11 ${sublist})"
      if [ "$?" -eq "0" ]; then
        if (find /usr/share/zoneinfo/"${ZONE}" -maxdepth 1 -type d |
            sed -n -e 's!^.*/!!p' | grep "${SUBZONE}" &>/dev/null); then
          sublist="$(find /usr/share/zoneinfo/"${ZONE}"/"${SUBZONE}" \
            -maxdepth 1 | sed -n -e 's!^.*/!!p' | sort | sed 's/$/ -/g' |
            grep -v "${SUBZONE}")"
          SUB_SUBZONE="$(dialog --stdout --ok-button "${ok}" --cancel-button \
            "${back}" --menu "\n${zone_msg1}" 15 60 7 ${sublist})"
          if [ "$?" -eq "0" ]; then
            ZONE="${ZONE}/${SUBZONE}/${SUB_SUBZONE}"
            break
          fi
        else
          ZONE="${ZONE}/${SUBZONE}"
          break
        fi
      fi
    else
      break
    fi
  done
  log "Set time zone to: ${ZONE}"
}

set_language() {
  op_title="Language Selection"
  local language="$(dialog --stdout --no-cancel --menu "\n${set_language_msg}" \
    20 60 10 \
    "English" "-" \
    "Bulgarian" "Български" \
    "Dutch" "Nederlands" \
    "French" "Français" \
    "German" "Deutsch" \
    "Greek" "Greek" \
    "Hungarian" "Magyar" \
    "Indonesian" "bahasa Indonesia" \
    "Italian" "Italiano" \
    "Latvian" "Latviešu" \
    "Lithuanian" "Lietuvių" \
    "Polish" "Polski" \
    "Portuguese" "Português" \
    "Portuguese-Brazilian" "Português do Brasil" \
    "Romanian" "Română" \
    "Russian" "Russian" \
    "Spanish" "Español" \
    "Swedish" "Svenska")"
  case "${language}" in
  "English")
    LANG_FILE="${GDL_DIR}"/lang/english.conf ;;
  "Bulgarian")
    LANG_FILE="${GDL_DIR}"/lang/bulgarian.conf lib=bg bro=bg ;;
  "Dutch")
    LANG_FILE="${GDL_DIR}"/lang/dutch.conf lib=nl bro=nl ;;
  "French")
    LANG_FILE="${GDL_DIR}"/lang/french.conf lib=fr bro=fr ;;
  "German")
    LANG_FILE="${GDL_DIR}"/lang/german.conf lib=de bro=de ;;
  "Greek")
    LANG_FILE="${GDL_DIR}"/lang/greek.conf lib=el bro=el ;;
  "Hungarian")
    LANG_FILE="${GDL_DIR}"/lang/hungarian.conf lib=hu bro=hu ;;
  "Indonesian")
    LANG_FILE="${GDL_DIR}"/lang/indonesia.conf lib=id bro=id ;;
  "Italian")
    LANG_FILE="${GDL_DIR}"/lang/italian.conf lib=it bro=it ;;
  "Latvian")
    LANG_FILE="${GDL_DIR}"/lang/latvian.conf lib=lv bro=lv ;;
  "Lithuanian")
    LANG_FILE="${GDL_DIR}"/lang/lithuanian.conf lib=lt bro=lt ;;
  "Polish")
    LANG_FILE="${GDL_DIR}"/lang/polish.conf lib=pl bro=pl ;;
  "Portuguese")
    LANG_FILE="${GDL_DIR}"/lang/portuguese.conf lib=pt bro=pt-pt ;;
  "Portuguese-Brazilian")
    LANG_FILE="${GDL_DIR}"/lang/portuguese-br.conf lib=pt-br bro=pt-br ;;
  "Romanian")
    LANG_FILE="${GDL_DIR}"/lang/romanian.conf lib=ro bro=ro ;;
  "Russian")
    LANG_FILE="${GDL_DIR}"/lang/russian.conf lib=ru bro=ru ;;
  "Spanish")
    LANG_FILE="${GDL_DIR}"/lang/spanish.conf lib=es bro=es-es ;;
  "Swedish")
    LANG_FILE="${GDL_DIR}"/lang/swedish.conf lib=sv bro=sv-se ;;
  esac
  source "${LANG_FILE}"
  RELOAD=true
  log "Set language to: ${language}"
}
