#!/usr/bin/env bash

grub_config() {
  if "${crypted}"; then
    sed -i 's!quiet!cryptdevice=/dev/lvm/lvroot:root root=/dev/mapper/root!' \
      /mnt/etc/default/grub
  else
    sed -i 's/quiet//' /mnt/etc/default/grub
  fi

  if "${drm}"; then
    sed -i '/GRUB_CMDLINE_LINUX_DEFAULT=/ s/.$/ nvidia-drm.modeset=1"/;s/" /"/'\
      /mnt/etc/default/grub
  fi

  if "${UEFI}"; then
    arch-chroot /mnt grub-install --efi-directory="${esp_mnt}" \
      --target=x86_64-efi --bootloader-id=boot |& tee -a LOG_FILE
    cp /mnt/"${esp_mnt}"/EFI/boot/grubx64.efi \
      /mnt/"${esp_mnt}"/EFI/boot/bootx64.efi

    if ! "${crypted}"; then
      arch-chroot /mnt mkinitcpio -p linux |& tee -a LOG_FILE
    fi
  else
    arch-chroot /mnt grub-install /dev/"${DRIVE}" |& tee -a LOG_FILE
  fi
  arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg |& tee -a LOG_FILE
}
