#!/usr/bin/env bash

final_system_check() {
  op_title="${complete_op_msg}"
  # Check if system is installed
  if "${INSTALLED}"; then
    # Check if a bootloader is installed
    if [ "${bootloader}" = "${none}" ]; then
      if (yesno "\n${complete_no_boot_msg}" "${yes}" "${no}"); then
        clear
        dragonsay "Type 'gdl' or 'exit' to return to the installer!"
        exit
      fi
    fi
    log "GDL installation process complete"
    cp "${LOG_FILE}" /mnt/root
    clear
    dragonsay "${install_complete_msg1}"
    echo -e "${install_complete_msg2}"
    exit
  else
    # Warn user install incomplete, prompt for reboot
    if (yesno "${not_complete_msg}" "${yes}" "${no}"); then
      clear
      umount -R /mnt
      reboot
      exit
    fi
  fi
}

main_menu() {
  op_title="${menu_op_msg}"
  while (true); do
    menu_item="$(dialog --stdout --nocancel --ok-button "${ok}" \
      --menu "${menu}" 19 60 8 \
      "${menu0}" "-" \
      "${menu1}" "-" \
      "${menu2}" "-" \
      "${menu3}" "-" \
      "${menu5}" "-" \
      "${menu11}" "-" \
      "${menu12}" "-")"
    case "${menu_item}" in
    "${menu0}") # Set system locale
      set_locale
      ;;
    "${menu1}") # Set system time zone
      set_zone
      ;;
    "${menu2}") # Set system keymap
      set_keys
      ;;
    "${menu3}") # Prepare drives check if mounted
      if "${mounted}"; then
        if (yesno "\n${menu_err_msg3}" "${yes}" "${no}" 1); then
          mounted=false
          prepare_drives
        fi
      else
        prepare_drives
      fi
      ;;
    "${menu5}") # Begin base install
      if "${mounted}"; then
        install_arch_linux
      elif (yesno "\n${install_err_msg1}" "${yes}" "${no}"); then
        prepare_drives
      fi
      ;;
    "${menu11}") # "Reboot" (final system status check)
      final_system_check
      ;;
    "${menu12}") # Exit installer
      if (yesno "\n${menu_exit_msg}" "${yes}" "${no}"); then
        clear
        dragonsay "Type 'gdl' or 'exit' to return to the installer!"
        exit
      fi
      ;;
    esac
  done
}
