#!/usr/bin/env bash

add_software() {
  software=""

  # Games
  op_title="${games}"
  software+=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" \
    --checklist "${software_msg1}" 20 70 10 \
    "steam" "${game10}" ON \
    "lutris" "Lutris game installer and launcher" ON \
    "supertuxkart" "${game6}" ON \
    "extremetuxracer" "Extreme Tux Racer" ON \
    "supertux" "${game5}" ON \
    "dwarffortress" "Build a dwarven outpost or play as an adventurer in a randomly generated world" ON \
    "xonotic" "${game9}" ON \
    "warsow" "${game8}" OFF \
    "bzflag" "${game2}" OFF \
    "open-adventure" "Port of the Colossal Cave Adventure text-based adventure game" OFF \
    "bsd-games2" "${game1}" OFF \
    "aisleriot" "${game11}" OFF 3>&1 1>&2 2>&3)" "
  if (grep <<<"${software}" "steam" &>/dev/null); then
    software+="steam-native-runtime "
  fi

  # Development software
  op_title="${program_msg}"
  software+=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" \
    --checklist "${software_msg1}" 20 63 10 \
    "godot" "Multi-platform 2D and 3D game engine" ON \
    "unityhub" "Manage Unity game engine installations and projects" ON \
    "android-studio" "" ON \
    "python-pygame" "" ON \
    "pygtk" "" ON \
    "python-distutils-extra" "" OFF \
    "ruby" "${prg12}" OFF \
    "jdk-openjdk" "${prg15}" OFF \
    "jdk8-openjdk" "${prg7}" OFF \
    "jdk11-openjdk" "${prg14}" OFF \
    "java-runtime-common" "${prg5}" OFF \
    "java-openjfx" "${prg8}" OFF \
    "php" "${prg10}" OFF \
    "clisp" "${prg0}" OFF \
    "dmd" "${prg1}" OFF \
    "dart" "${prg2}" OFF \
    "go" "${prg3}" OFF \
    "go-tools" "${prg4}" OFF \
    "perl" "${prg9}" OFF \
    "scala" "${prg13}" OFF 3>&1 1>&2 2>&3)" "

  # Graphics/drawing/modeling software
  op_title="${graphic_msg}"
  software+=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" \
    --checklist "${software_msg1}" 20 63 10 \
    "gimp" "${graphic2}" ON \
    "inkscape" "${graphic9}" ON \
    "blender" "${graphic0}" ON \
    "aseprite" "Create animated sprites and pixel art" OFF \
    "mtpaint" "${graphic10}" OFF \
    "mypaint" "${graphic11}" OFF \
    "graphicsmagick" "${graphic8}" OFF \
    "graphviz" "${graphic3}" OFF \
    "imagemagick" "${graphic4}" OFF \
    "darktable" "${graphic1}" OFF \
    "rawtherapee" "${graphic7}" OFF 3>&1 1>&2 2>&3)" "

  # Multimedia software
  op_title="${multimedia_msg}"
  software+=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" \
    --checklist "${software_msg1}" 20 63 10 \
    "vlc" "${media6}" ON \
    "multimedia-codecs" "${media8}" ON \
    "obs-studio" "Free software for live streaming and recording" ON \
    "openshot" "An award-winning free and open-source video editor" ON \
    "kdenlive" "${media9}" OFF \
    "pitivi" "${media2}" OFF \
    "simplescreenrecorder" "${media3}" OFF \
    "byzanz" "${media10}" OFF \
    "handbrake" "${media0}" OFF \
    "mplayer" "${media1}" OFF \
    "mpv" "${media7}" OFF \
    "smplayer" "${media4}" OFF \
    "snappy-player" "${media11}" OFF \
    "totem" "${media5}" OFF \
    "youtube-dl" "${media12}" OFF 3>&1 1>&2 2>&3)" "
#  if (grep <<<"${software}" "vlc"); then
#    software+="qt5 phonon-qt5-vlc " #vlc-plugin-fluidsynth
#  fi
  if (grep <<<"${software}" "multimedia-codecs"); then
    software=$(sed <<<"${software}" 's/multimedia-codecs/gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly ffmpegthumbnailer gst-libav/')
  fi

  # Audio software
  op_title="${audio_msg}"
  software+=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" \
    --checklist "${software_msg1}" 20 63 10 \
    "audacity" "${audio0}" ON \
    "audacious" "${audio1}" OFF \
    "clementine" "${audio10}" OFF \
    "cmus" "${audio2}" OFF \
    "jack2" "${audio3}" OFF \
    "projectm" "${audio4}" OFF \
    "lmms" "${audio5}" OFF \
    "mpd" "${audio6}" OFF \
    "ncmpcpp" "${audio7}" OFF \
    "pianobar" "${audio9}" OFF \
    "pavucontrol" "${audio8}" OFF \
    "pulseaudio-equalizer" "${audio11}" OFF \
    "qmmp" "${audio13}" OFF \
    "rhythmbox" "${audio14}" OFF 3>&1 1>&2 2>&3)" "

  # Internet software
  op_title="${internet_msg}"
  software+=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" \
    --checklist "${software_msg1}" 20 63 10 \
    "firefox" "${net2}" ON \
    "chromium" "${net0}" ON \
    "transmission-gtk" "${net8}" ON \
    "hexchat" "${net11}" ON \
    "opera" "${net5}" OFF \
    "elinks" "${net3}" OFF \
    "lynx" "${net3}" OFF \
    "irssi" "${net9}" OFF \
    "midori" "${net12}" OFF \
    "minitube" "${net4}" OFF \
    "filezilla" "${net1}" OFF \
    "thunderbird" "${net6}" OFF 3>&1 1>&2 2>&3)" "
  if (grep <<<"${software}" "firefox" &>/dev/null) && [ -n "${bro}" ]; then
    software+="firefox-i18n-${bro} "
  fi
  if (grep <<<"${software}" "thunderbird" &>/dev/null) && [ -n "${bro}" ] &&
      [ "${bro}" != "lv" ]; then
    software+="thunderbird-i18n-${bro} "
  fi

  # Office software
  op_title="${office_msg}"
  software+=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" \
    --checklist "${software_msg1}" 20 63 10 \
    "libreoffice-fresh" "${office4}" ON \
    "libreoffice-still" "${office5}" OFF \
    "abiword" "${office0}" OFF \
    "calligra" "${office1}" OFF \
    "evince" "${office9}" OFF \
    "gnumeric" "${office3}" OFF \
    "glabels" "${office10}" OFF \
    "gobby" "${office8}" OFF \
    "mupdf" "${office6}" OFF \
    "scribus" "${office11}" OFF \
    "zathura" "${office7}" OFF 3>&1 1>&2 2>&3)" "
  if (grep <<<"${software}" "libreoffice-fresh" &>/dev/null) &&
      [ -n "${lib}" ]; then
    software+="libreoffice-fresh-${lib} "
  fi
  if (grep <<<"${software}" "libreoffice-still" &>/dev/null) &&
      [ -n "${lib}" ]; then
    software+="libreoffice-still-${lib} "
  fi

  # Text editors
  op_title="${text_editor}"
  software+=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" \
    --checklist "${software_msg1}" 20 63 10 \
    "atom" "${edit7}" ON \
    "emacs" "${edit0}" OFF \
    "geany" "${edit1}" OFF \
    "gedit" "${edit2}" OFF \
    "gvim" "${edit3}" OFF \
    "mousepad" "${edit4}" OFF \
    "neovim" "${edit5}" OFF \
    "vim" "${edit6}" OFF \
    "zim" "${edit8}" OFF 3>&1 1>&2 2>&3)" "

  # Fonts
  op_title="${fonts}"
  software+=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" \
    --checklist "${software_msg1}" 20 63 10 \
    "bdf-unifont" "${font0}" OFF \
    "noto-fonts-cjk" "${font1}" OFF 3>&1 1>&2 2>&3)" "

  # Terminals
  op_title="${terminal_msg}"
  software+=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" \
    --checklist "${software_msg1}" 20 63 10 \
    "terminator" "${term5}" ON \
    "cool-retro-term" "${term12}" ON \
    "guake" "${term1}" OFF \
    "kmscon" "${term2}" OFF \
    "pantheon-terminal" "${term3}" OFF \
    "rxvt-unicode" "${term4}" OFF \
    "screen" "${sys11}" OFF \
    "terminology" "${term10}" OFF \
    "termite" "${term9}" OFF \
    "tilda" "${term11}" OFF \
    "tilix" "${term13}" oFF \
    "tmux" "${sys14}" OFF \
    "xfce4-terminal" "${term6}" OFF \
    "yakuake" "${term7}" OFF 3>&1 1>&2 2>&3)" "

  # Utilities
  op_title="${util}"
  software+=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" \
    --checklist "${software_msg1}" 20 65 10 \
    "htop" "${sys6}" ON \
    "gparted" "${sys4}" ON \
    "wget" "${sys18}" ON \
    "bc" "${sys25}" OFF \
    "bleachbit" "${sys22}" OFF \
    "conky" "${sys2}" OFF \
    "dmenu" "${sys19}" OFF \
    "galculator" "${sys24}" OFF \
    "gnome-packagekit" "${sys26}" OFF \
    "gnome-software" "${sys27}" OFF \
    "gpm" "${sys5}" OFF \
    "k3b" "${sys8}" OFF \
    "nmap" "${sys9}" OFF \
    "ntfs-3g" "${sys28}" OFF \
    "pcmanfm" "${sys21}" OFF \
    "ranger" "${sys20}" OFF \
    "scrot" "${sys13}" OFF \
    "tuxcmd" "${sys15}" OFF \
    "virtualbox" "${sys16}" OFF \
    "xscreensaver" "${sys34}" OFF 3>&1 1>&2 2>&3)" "

  op_title="${software_op_msg}"
  if [ -z "${software}" ]; then
    if ! (yesno "\n${software_noconfirm_msg} ${software_menu}?" "${yes}" \
        "${no}" 1); then
      skip=true
    fi
  else
    new_software=$(echo "${software}" | sed 's/\"//g')
    software_list=$(echo "${new_software}" | sed -e 's/^[ \t]*//')
    pacman -Sy --print-format='%s' "${new_software}" | awk \
      '{s+=$1} END {print s/1024/1024}' >/tmp/size &
    pid=$! pri=0.1 msg="${wait_load}\n\n \Z1> \Z3pacman -Sy --print-format\Zn" \
      load
    download_size=$(</tmp/size)
    rm /tmp/size
    software_size=$(sed <<<"${download_size}" 's/\(\..\)\(.*\)/\1 MiB/')
    software_int=$(echo "${new_software}" | wc -w)
    source "${lang_file}"
    if [ "${software_int}" -lt "15" ]; then
      height=14
    else
      height=16
    fi
    final_software+="${software} "
  fi

  # Install all selected software
  if [ -z "${final_software}" ]; then
    if (yesno "\n${software_warn_msg}" "${yes}" "${no}" 1); then
      break
    fi
  else
    download=$(echo "${final_software}" | sed 's/\"//g' | tr ' ' '\n' | nl | \
      sort -u -k2 | sort -n | cut -f2- | sed 's/$/ /g' | tr -d '\n')
    download_list=$(echo "${download}" | sed -e 's/^[ \t]*//')
    log "Add software list: ${download}"
    base_install+="${download_list} "
    unset final_software
    break
  fi
}
