#!/bin/bash

update_mirrors() {
  check_connection
  op_title="${mirror_op_msg}"
  local edit_mirrors
  edit_mirrors="$(dialog --stdout --ok-button "${ok}" \
    --menu "\n${mirror_msg0}" 12 60 3 \
    "${cancel_mirrors}" "->" \
    "${update_mirrors_msg}" "->" \
    "${manual_mirrors}" "->")"
  case "${edit_mirrors}" in
  "${update_mirrors_msg}") # update mirrors automatically via reflector
    clear
    dragonsay "Updating mirrors..." |& tee -a "${LOG_FILE}"
    reflector --verbose --latest 20 --sort rate --save /etc/pacman.d/mirrorlist
    ;;
  "${manual_mirrors}") # update mirrors manually via text editor
    local editor
    if editor="$(dialog --stdout --ok-button "${ok}" \
        --menu "\n${mirror_editor_msg}" 10 60 4 \
        "nano" "${nano_msg}" \
        "vim" "${vim_msg}" \
        "${cancel}" "->")" && [ "${editor}" != "${cancel}" ]; then
      "${editor}" /etc/pacman.d/mirrorlist
    fi
    ;;
  esac
}
