#!/usr/bin/env bash

graphics() {
  op_title="${de_op_msg}"
  while (true); do
    de=$(dialog --ok-button "${done_msg}" --cancel-button "${cancel}" --menu "\n${environment_msg}" 10 60 5 \
      "gdl-gnome" "${de0}" \
      "gdl-cinnamon" "${de1}" \
      "gdl-xfce" "${de2}" 3>&1 1>&2 2>&3)
    if [ -n "${de}" ]; then
      break
    fi
  done

  source "${lang_file}"

  while read -r env; do
    case "${env}" in
    "gdl-gnome")
      start_term="exec gnome-session"
      DE+="gnome gnome-extra "
      DM="gdm"
      ;;
    "gdl-cinnamon")
      start_term="exec cinnamon-session"
      DE+="cinnamon cinnamon-translations gnome-screenshot file-roller p7zip zip unrar "
      ;;
    "gdl-xfce")
      start_term="exec startxfce4"
      DE+="xfce4 xfce4-goodies file-roller p7zip zip unrar "
      ;;
    esac
    if [ "${env}" != "gdl-gnome" ]; then
      DE+="lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings "
    fi
  done <<<"${de}"

  while (true); do
    if "${VM}"; then
      case "${virt}" in
      qemu)
        GPU="spice-vdagent "
        log "Added QEMU guest utils"
        ;;
      vbox)
        GPU="virtualbox-guest-utils virtualbox-guest-dkms "
        log "Added VirtualBox guest utils"
        ;;
      vmware)
        GPU="xf86-video-vmware xf86-input-vmmouse open-vm-tools net-tools gtkmm mesa mesa-libgl"
        log "Added VMware guest utils"
        ;;
      hyper-v)
        GPU="xf86-video-fbdev mesa-libgl"
        log "Added HyperV guest utils"
        ;;
      *)
        GPU="xf86-video-fbdev mesa-libgl"
        log "Added generic VM guest utils"
        ;;
      esac
      break
    fi

    if "${NVIDIA}"; then
      GPU=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" --menu "${graphics_msg}" 18 60 6 \
        "${default}" "${gr0}" \
        "xf86-video-ati" "${gr4}" \
        "xf86-video-amdgpu" "${gr10}" \
        "xf86-video-intel" "${gr5}" \
        "xf86-video-nouveau" "${gr8}" \
        "xf86-video-vesa" "${gr1}" \
        "NVIDIA" "${gr2} ->" 3>&1 1>&2 2>&3)
      ex="$?"
    else
      GPU=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" --menu "${graphics_msg}" 17 60 5 \
        "${default}" "${gr0}" \
        "xf86-video-ati" "${gr4}" \
        "xf86-video-amdgpu" "${gr10}" \
        "xf86-video-intel" "${gr5}" \
        "xf86-video-nouveau" "${gr8}" \
        "xf86-video-vesa" "${gr1}" 3>&1 1>&2 2>&3)
      ex="$?"
    fi

    if [ "${GPU}" = "NVIDIA" ]; then
      GPU=$(dialog --ok-button "${ok}" --cancel-button "${cancel}" --menu "${nvidia_msg}" 15 60 4 \
        "${gr0}" "->" \
        "nvidia" "${gr6}" \
        "nvidia-390xx" "${gr9}" \
        "nvidia-340xx" "${gr7}" 3>&1 1>&2 2>&3)
      if [ "$?" -eq "0" ]; then
        if [ "${GPU}" = "${gr0}" ]; then
          pci_id=$(lspci -nn | grep "VGA" | egrep -o '\[.*\]' | awk '{print $NF}' | sed 's/.*://;s/]//')
          if (grep <"${gdl_directory}"/etc/nvidia390.xx "${pci_id}" &>/dev/null); then
            if (yesno "\n${nvidia_390msg}" "${yes}" "${no}"); then
              GPU="nvidia-390xx nvidia-390xx-libgl nvidia-390xx-utils nvidia-settings"
              break
            fi
          elif (grep <"${gdl_directory}"/etc/nvidia340.xx "${pci_id}" &>/dev/null); then
            if (yesno "\n${nvidia_340msg}" "${yes}" "${no}"); then
              GPU="nvidia-340xx nvidia-340xx-libgl nvidia-340xx-utils nvidia-settings"
              break
            fi
          elif (yesno "\n${nvidia_curmsg}" "${yes}" "${no}"); then
            GPU="nvidia"
            if (yesno "\n${nvidia_modeset_msg}" "${yes}" "${no}"); then
              drm=true
            fi
            GPU+=" nvidia-libgl nvidia-utils lib32-nvidia-utils nvidia-settings"
            break
          fi
        elif [ "${GPU}" = "nvidia" ]; then
          if (yesno "\n${nvidia_modeset_msg}" "${yes}" "${no}"); then
            drm=true
          fi
          GPU+=" ${GPU}-libgl ${GPU}-utils"
          break
        else
          GPU+=" ${GPU}-libgl ${GPU}-utils"
          break
        fi
      fi
    elif [ "${GPU}" = "${default}" ]; then
      GPU="${default_GPU} mesa-libgl"
      break
    else
      GPU+=" mesa-libgl"
      break
    fi
  done

  DE+="${GPU} "

  if (yesno "\n${touchpad_msg}" "${yes}" "${no}"); then
    if (grep <<<"${DE}" "gnome" &>/dev/null); then
      DE+="xf86-input-libinput "
    else
      DE+="xf86-input-synaptics "
    fi
  fi

  if "${enable_bt}"; then
    if (yesno "\n${blueman_msg}" "${yes}" "${no}"); then
      DE+="blueman "
    fi
  fi

  base_install+="${DE} "
}

config_env() {
  arch-chroot "${ARCH}" fc-cache -f
  cp "${gdl_directory}"/extra/gdl-icon.png "${ARCH}"/root/.face
  cp "${gdl_directory}"/extra/gdl-icon.png "${ARCH}"/etc/skel/.face
  cp "${gdl_directory}"/extra/gdl-icon.png "${ARCH}"/usr/share/pixmaps
  mkdir "${ARCH}"/usr/share/backgrounds/gdl
  cp -r "${gdl_directory}"/extra/wallpapers/* "${ARCH}"/usr/share/backgrounds/gdl/
  cp -r "${gdl_directory}/extra/desktop/${env}/*" -t "${ARCH}"/root
  cp -r "${gdl_directory}/extra/desktop/${env}/.config" -t "${ARCH}"/etc/skel
  cp -r "${gdl_directory}/extra/desktop/.config" -t "${ARCH}"/etc/skel
#  case "${env}" in
#  "gdl-gnome")
#    cp -r "${gdl_directory}/extra/desktop/gdl-gnome/gnome-backgrounds.xml" "${ARCH}"/usr/share/gnome-background-properties
#    ;;
#  esac
  log "Configured: ${env}"
}
