#!/bin/bash

install_base() {
  op_title="${install_op_msg}"
  if [ -n "${lib}" ]; then
    base_install+="libreoffice-fresh-${lib} "
  fi
  base_install=$(tr <<<"${base_install}" " " "\n" | sort | uniq | tr "\n" " ")
  clear
  dragonsay "Installing base packages..." | tee -a "${LOG_FILE}"
  pacman -Sy
  pacstrap /mnt --overwrite ${base_install} |& tee -a "${LOG_FILE}"
  if [ "$?" -eq "0" ]; then
    INSTALLED=true
    log "Completed base installation"
  else
    report_error
    clear
    dragonsay "${how_to_relaunch_installer}"
    exit 1
  fi
  genfstab -U -p /mnt >>/mnt/etc/fstab |& tee -a "${LOG_FILE}"
  log "Generated fstab"
  grub_config
  log "Configured grub"
}

prepare_base() {
  op_title="${install_op_msg}"
  base_install="${default_packages} ${UCODE} "
  if "${WIFI_AVAILABLE}" ||
      (yesno "\n${wifi_option_msg}" "${yes}" "${no}" 1); then
    base_install+="wireless_tools wpa_supplicant "
    log "Added wireless utilities"
  fi
  if "${BLUETOOTH_AVAILABLE}" &&
      (yesno "\n${bluetooth_msg}" "${yes}" "${no}" 1); then
    base_install+="bluez bluez-utils pulseaudio-bluetooth "
    BLUETOOTH_ENABLED=true
    log "Added bluetooth support"
  fi
  if (yesno "\n${os_prober_msg}" "${yes}" "${no}" 1); then
    base_install+="os-prober "
    log "Added os-prober"
  fi
  if "${ENABLE_F2FS}"; then
    base_install+="f2fs-tools "
    log "Added f2fs-tools"
  fi
  if "${UEFI}"; then
    base_install+="efibootmgr "
    log "Added efibootmgr"
  fi
}
