#!/bin/bash

set_desktop_and_graphics_settings() {
  op_title="${de_op_msg}"
  while (true); do
    de=$(dialog --stdout --ok-button "${done_msg}" --cancel-button "${cancel}" \
      --menu "\n${environment_msg}" 14 60 6 \
      "gdl-gnome" "${de0}" \
      "gdl-cinnamon" "${de1}" \
      "gdl-xfce" "${de2}")
    if [ -n "${de}" ]; then
      break
    fi
  done

  source "${LANG_FILE}"

  case "${de}" in
  "gdl-gnome")
    start_term="exec gnome-session"
    DE+="gnome gnome-extra variety "
    DM="gdm"
    ;;
  "gdl-cinnamon")
    start_term="exec cinnamon-session"
    DE+="cinnamon cinnamon-translations gnome-screenshot gnome-calculator
      file-roller nemo-fileroller p7zip zip unrar xed xreader " #gnome-terminal redshift
    additional_packages+="xviewer xplayer pix clipit "
    ;;
  "gdl-xfce")
    start_term="exec startxfce4"
    DE+="xfce4 xfce4-goodies file-roller p7zip zip unrar galculator "
    additional_packages+="mugshot "
    ;;
  esac
  if [ "${de}" != "gdl-gnome" ]; then
    DE+="lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings "
  fi

  while (true); do
    GPU=""
    if "${VM}"; then
      case "${virt}" in
      qemu)
        GPU="spice-vdagent"
        log "Added QEMU guest utils"
        ;;
      vbox)
        GPU="virtualbox-guest-utils virtualbox-guest-dkms"
        log "Added VirtualBox guest utils"
        ;;
      vmware)
        GPU="xf86-video-vmware xf86-input-vmmouse open-vm-tools net-tools gtkmm"
        log "Added VMware guest utils"
        ;;
      hyper-v)
        GPU="xf86-video-fbdev"
        log "Added HyperV guest utils"
        ;;
      *)
        GPU="xf86-video-fbdev"
        log "Added generic VM guest utils"
        ;;
      esac
      break
    fi

    if "${NVIDIA}"; then
      GPU=$(dialog --stdout --ok-button "${ok}" --cancel-button "${cancel}" \
        --menu "${graphics_msg}" 18 60 6 \
        "${default}" "${gr0}" \
        "xf86-video-ati" "${gr4}" \
        "xf86-video-amdgpu" "${gr10}" \
        "xf86-video-intel" "${gr5}" \
        "xf86-video-nouveau" "${gr8}" \
        "xf86-video-vesa" "${gr1}" \
        "nvidia" "${gr2} ->")
      ex="$?"
    else
      GPU=$(dialog --stdout --ok-button "${ok}" --cancel-button "${cancel}" \
        --menu "${graphics_msg}" 17 60 5 \
        "${default}" "${gr0}" \
        "xf86-video-ati" "${gr4}" \
        "xf86-video-amdgpu" "${gr10}" \
        "xf86-video-intel" "${gr5}" \
        "xf86-video-nouveau" "${gr8}" \
        "xf86-video-vesa" "${gr1}")
      ex="$?"
    fi

    if [ "${GPU}" = "${default}" ]; then
      GPU="${default_GPU}"
    fi
    if [ "${GPU}" = "nvidia" ]; then
      GPU+=" nvidia-libgl nvidia-utils lib32-nvidia-utils nvidia-settings
        nvidia-prime nvidia-dkms"
      NVIDIA_DRM=true
      break
    elif [ -n "${GPU}" ]; then
      if [ "${GPU}" = "xf86-video-ati" ] ||
         [ "${GPU}" = "xf86-video-amdgpu" ]; then
        GPU+=" vulkan-radeon lib32-vulkan-radeon"
      elif [ "${GPU}" = "xf86-video-intel" ]; then
        GPU+=" vulkan-intel lib32-vulkan-intel lib32-libva-intel-driver"
      fi
      break
    fi
  done

  DE+="${GPU} mesa lib32-mesa "

  if (yesno "\n${touchpad_msg}" "${yes}" "${no}"); then
    if (grep <<<"${DE}" "gnome" &>/dev/null); then
      DE+="xf86-input-libinput "
    else
      DE+="xf86-input-synaptics "
    fi
  fi

  if "${BLUETOOTH_ENABLED}"; then
    if (yesno "\n${blueman_msg}" "${yes}" "${no}"); then
      DE+="blueman "
    fi
  fi

  base_install+="${DE} "
}

configure_desktop_environment() {
  arch-chroot /mnt fc-cache -f # build font information cache files
  cp "${GDL_DIR}"/extra/gdl-icon.png /mnt/root/.face
  cp "${GDL_DIR}"/extra/gdl-icon.png "${SKEL_DIR}"/.face
  cp "${GDL_DIR}"/extra/gdl-icon.png /mnt/usr/share/pixmaps
  mkdir /mnt/usr/share/backgrounds/gdl
  cp -r "${GDL_DIR}"/extra/wallpapers/* /mnt/usr/share/backgrounds/gdl/
  cp -r "${GDL_DIR}"/extra/.config "${SKEL_DIR}"
  case "${de}" in
  "gdl-gnome")
    cp -r "${GDL_DIR}"/extra/gnome/.config "${SKEL_DIR}"
    ;;
  "gdl-cinnamon")
    cp -r "${GDL_DIR}"/extra/cinnamon/.c* "${SKEL_DIR}"
    ;;
  "gdl-xfce")
    cp -r "${GDL_DIR}"/extra/xfce/.config "${SKEL_DIR}"
    ;;
  esac
  log "Configured desktop environment: ${de}"
}
