#!/usr/bin/env bash

get_connection_info() {
  op_title="${connection_op_msg}"
  (
    test_mirror="$(grep </etc/pacman.d/mirrorlist "^Server" | awk 'NR==1{print $3}' | sed 's/$.*//')"
    test_pkg="$(curl -s https://www.archlinux.org/packages/extra/x86_64/bluez-utils/ | grep "<title>" | awk '{print $4"-"$5}')"
    test_link="${test_mirror}extra/os/x86_64/${test_pkg}-x86_64.pkg.tar.zst"
    wget -4 --no-check-certificate --append-output=/tmp/wget.log -O /dev/null "${test_link}"
  ) &
  pid=$! pri=0.3 msg="\n${connection_load} \n\n \Z1> \Z3wget -O /dev/null test_link/test1Mb.db\Zn" load

  sed -i 's/\,/\./' /tmp/wget.log
  connection_speed="$(tail /tmp/wget.log | grep -oP '(?<=\().*(?=\))' | awk '{print $1}')"
  connection_rate="$(tail /tmp/wget.log | grep -oP '(?<=\().*(?=\))' | awk '{print $2}')"

  if (lscpu | grep "max MHz" &>/dev/null); then
    cpu_mhz="$(lscpu | grep "CPU max MHz" | awk '{print $4}' | sed 's/\..*//')"
  else
    cpu_mhz="$(lscpu | grep "CPU MHz" | awk '{print $3}' | sed 's/\..*//')"
  fi

  case "${cpu_mhz}" in
  [0-9][0-9][0-9])
    cpu_sleep=4.5
    ;;
  [1][0-9][0-9][0-9])
    cpu_sleep=4
    ;;
  [2][0-9][0-9][0-9])
    cpu_sleep=3.5
    ;;
  *)
    cpu_sleep=2.5
    ;;
  esac

  export connection_speed connection_rate cpu_sleep
  log "Ranked connection speed: ${connection_speed} ${connection_rate}"
  log "Clocked CPU MHz: ${cpu_mhz}"
  rm /tmp/wget.log &>/dev/null
}
