#!/usr/bin/env bash

set_locale() {
  op_title="${locale_op_msg}"

  while (true); do
    LOCALE="$(dialog --nocancel --ok-button "${ok}" --menu "${locale_msg}" 18 60 11 \
      "en_US.UTF-8" "United States" \
      "en_AU.UTF-8" "Australia" \
      "pt_BR.UTF-8" "Brazil" \
      "en_CA.UTF-8" "Canada" \
      "es_ES.UTF-8" "Spanish" \
      "fr_FR.UTF-8" "French" \
      "de_DE.UTF-8" "German" \
      "el_GR.UTF-8" "Greek" \
      "en_GB.UTF-8" "Great Britain" \
      "hu_HU.UTF-8" "Hungary" \
      "it_IT.UTF-8" "Italian" \
      "lv_LV.UTF-8" "Latvian" \
      "es_MX.UTF-8" "Mexico" \
      "pt_PT.UTF-8" "Portugal" \
      "ro_RO.UTF-8" "Romanian" \
      "ru_RU.UTF-8" "Russian" \
      "es_ES.UTF-8" "Spanish" \
      "sv_SE.UTF-8" "Swedish" \
      "${other}" "${other}-locale" 3>&1 1>&2 2>&3)"

    if [ "${LOCALE}" = "${other}" ]; then
      LOCALE="$(dialog --ok-button "${ok}" --cancel-button "${cancel}" --menu "${locale_msg}" 18 60 11 ${localelist} 3>&1 1>&2 2>&3)"

      if [ "$?" -eq "0" ]; then
        break
      fi
    else
      break
    fi
  done

  log "Set locale to: ${LOCALE}"
}

set_zone() {
  op_title="${zone_op_msg}"
  while (true); do
    ZONE="$(dialog --nocancel --ok-button "${ok}" --menu "${zone_msg0}" 18 60 11 ${zonelist} 3>&1 1>&2 2>&3)"
    if (find /usr/share/zoneinfo -maxdepth 1 -type d | sed -n -e 's!^.*/!!p' | grep "${ZONE}" &>/dev/null); then
      sublist="$(find /usr/share/zoneinfo/"${ZONE}" -maxdepth 1 | sed -n -e 's!^.*/!!p' | sort | sed 's/$/ -/g' | grep -v "${ZONE}")"
      SUBZONE="$(dialog --ok-button "${ok}" --cancel-button "${back}" --menu "${zone_msg1}" 18 60 11 ${sublist} 3>&1 1>&2 2>&3)"
      if [ "$?" -eq "0" ]; then
        if (find /usr/share/zoneinfo/"${ZONE}" -maxdepth 1 -type d | sed -n -e 's!^.*/!!p' | grep "${SUBZONE}" &>/dev/null); then
          sublist="$(find /usr/share/zoneinfo/"${ZONE}"/"${SUBZONE}" -maxdepth 1 | sed -n -e 's!^.*/!!p' | sort | sed 's/$/ -/g' | grep -v "${SUBZONE}")"
          SUB_SUBZONE="$(dialog --ok-button "${ok}" --cancel-button "${back}" --menu "${zone_msg1}" 15 60 7 ${sublist} 3>&1 1>&2 2>&3)"
          if [ "$?" -eq "0" ]; then
            ZONE="${ZONE}/${SUBZONE}/${SUB_SUBZONE}"
            break
          fi
        else
          ZONE="${ZONE}/${SUBZONE}"
          break
        fi
      fi
    else
      break
    fi
  done

  log "Set time zone to: ${ZONE}"
}

language() {
  log "Start gdl installer"
  op_title=" -| Language Selection |- "
  ILANG="$(dialog --nocancel --menu "\nWelcome to the GDL Arch installer!\n\n \Z3*\Zn Select your install language:" 20 60 10 \
    "English" "-" \
    "Bulgarian" "Български" \
    "Dutch" "Nederlands" \
    "French" "Français" \
    "German" "Deutsch" \
    "Greek" "Greek" \
    "Hungarian" "Magyar" \
    "Indonesian" "bahasa Indonesia" \
    "Italian" "Italiano" \
    "Latvian" "Latviešu" \
    "Lithuanian" "Lietuvių" \
    "Polish" "Polski" \
    "Portuguese" "Português" \
    "Portuguese-Brazilian" "Português do Brasil" \
    "Romanian" "Română" \
    "Russian" "Russian" \
    "Spanish" "Español" \
    "Swedish" "Svenska" 3>&1 1>&2 2>&3)"

  case "${ILANG}" in
  "English") export lang_file="${gdl_directory}"/lang/english.conf ;;
  "Bulgarian") export lang_file="${gdl_directory}"/lang/bulgarian.conf lib=bg bro=bg ;;
  "Dutch") export lang_file="${gdl_directory}"/lang/dutch.conf lib=nl bro=nl ;;
  "French") export lang_file="${gdl_directory}"/lang/french.conf lib=fr bro=fr ;;
  "German") export lang_file="${gdl_directory}"/lang/german.conf lib=de bro=de ;;
  "Greek") export lang_file="${gdl_directory}"/lang/greek.conf lib=el bro=el ;;
  "Hungarian") export lang_file="${gdl_directory}"/lang/hungarian.conf lib=hu bro=hu ;;
  "Indonesian") export lang_file="${gdl_directory}"/lang/indonesia.conf lib=id bro=id ;;
  "Italian") export lang_file="${gdl_directory}"/lang/italian.conf lib=it bro=it ;;
  "Latvian") export lang_file="${gdl_directory}"/lang/latvian.conf lib=lv bro=lv ;;
  "Lithuanian") export lang_file="${gdl_directory}"/lang/lithuanian.conf lib=lt bro=lt ;;
  "Polish") export lang_file="${gdl_directory}"/lang/polish.conf lib=pl bro=pl ;;
  "Portuguese") export lang_file="${gdl_directory}"/lang/portuguese.conf lib=pt bro=pt-pt ;;
  "Portuguese-Brazilian") export lang_file="${gdl_directory}"/lang/portuguese-br.conf lib=pt-br bro=pt-br ;;
  "Romanian") export lang_file="${gdl_directory}"/lang/romanian.conf lib=ro bro=ro ;;
  "Russian") export lang_file="${gdl_directory}"/lang/russian.conf lib=ru bro=ru ;;
  "Spanish") export lang_file="${gdl_directory}"/lang/spanish.conf lib=es bro=es-es ;;
  "Swedish") export lang_file="${gdl_directory}"/lang/swedish.conf lib=sv bro=sv-se ;;
  esac
}
