#!/bin/bash
#
# Golden Drake Linux (GDL) desktop environment customization script, for user
# settings best changed via command rather than config file. This script runs
# once, at user's first login, then self-destructs.
#
# Copyright (C) 2021-2024 Golden Drake Studios: goldendrakestudios.com

main() {
  sed -i '/gdl-config-script/d' ~/.bashrc
  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

  # KDE Plasma
  if [[ "${XDG_SESSION_DESKTOP@L}" =~ kde ]]; then
    plasma-apply-lookandfeel -a org.kde.breezedark.desktop
    plasma-apply-cursortheme Breeze_Amber
    /usr/lib/plasma-changeicons BeautyLine
    if pacman -Qs matchama; then
      plasma-apply-desktoptheme Matchama-Adaptive-Colors
      plasma-apply-colorscheme MatchamaDarkAliz
      echo -e "[KSplash]\nTheme=com.gitlab.cscs.matchama-dark" > \
        ~/.config/ksplashrc
    fi

  # GNOME
  elif [[ "${XDG_SESSION_DESKTOP@L}" =~ gnome ]]; then
    # gnome desktop
    gsettings set org.gnome.desktop.background picture-uri \
      'file:///usr/share/backgrounds/gdl/gds-logo-dark-1920x1080.jpg'
    gsettings set org.gnome.desktop.interface gtk-theme Matcha-dark-aliz
    gsettings set org.gnome.desktop.interface icon-theme BeautyLine
    gsettings set org.gnome.desktop.interface cursor-theme Breeze_Amber
    gsettings set org.gnome.desktop.interface accent-color yellow
    gsettings set org.gnome.desktop.interface clock-format 24h
    gsettings set org.gnome.desktop.interface clock-show-weekday true
    gsettings set org.gnome.desktop.interface clock-show-seconds true
    gsettings set org.gnome.desktop.interface show-battery-percentage true
    gsettings set org.gnome.desktop.interface enable-hot-corners false
    gsettings set org.gnome.desktop.peripherals.mouse speed 1.0
    gsettings set org.gnome.desktop.peripherals.touchpad speed 1.0
    gsettings set org.gnome.desktop.notifications show-in-lock-screen false
    gsettings set org.gnome.desktop.screensaver lock-delay 30
    gsettings set org.gnome.desktop.screensaver picture-uri \
      'file:///usr/share/backgrounds/gdl/gds-logo-dark-1920x1080.jpg'
    gsettings set org.gnome.desktop.session idle-delay 600
    gsettings set org.gnome.desktop.wm.preferences num-workspaces 2
    gsettings set org.gnome.desktop.wm.preferences button-layout \
      'appmenu:minimize,maximize,close'
    gsettings set org.gnome.desktop.wm.keybindings panel-run-dialog \
      "['<Super>r']"
    gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"
    gsettings set org.gnome.desktop.input-sources xkb-options \
      "['numpad:microsoft']"
    pacman -Q ibus &>/dev/null \
      && gsettings set org.gnome.desktop.interface gtk-im-module ibus

    # gnome shell
    gsettings set org.gnome.shell.app-switcher current-workspace-only true
    gsettings set org.gnome.shell.keybindings toggle-overview '@as []'
    gsettings set org.gnome.shell.keybindings toggle-quick-settings '@as []'
    gsettings set org.gnome.shell enabled-extensions "[
      'appindicatorsupport@rgcjonas.gmail.com',
      'dash-to-panel@jderose9.github.com',
      'launch-new-instance@gnome-shell-extensions.gcampax.github.com',
      'pano@elhan.io',
      'transparent-window-moving@noobsai.github.com',
      'user-theme@gnome-shell-extensions.gcampax.github.com',
      'workspace-indicator@gnome-shell-extensions.gcampax.github.com']"
    gsettings set org.gnome.shell.extensions.user-theme name Matcha-dark-aliz
    gsettings set org.gnome.shell.extensions.dash-to-panel \
      hide-overview-on-startup true
    gsettings set org.gnome.shell.extensions.dash-to-panel panel-positions \
      '{"0":"TOP"}'
    gsettings set org.gnome.shell.extensions.dash-to-panel panel-sizes \
      '{"0":36}'
    gsettings set org.gnome.shell.extensions.dash-to-panel show-apps-icon-file \
      '/usr/share/pixmaps/gdl-small.png'
    gsettings set org.gnome.shell.extensions.dash-to-panel show-favorites false
    gsettings set org.gnome.shell.extensions.dash-to-panel dot-style-unfocused \
      DOTS
    gsettings set org.gnome.shell.extensions.dash-to-panel click-action \
      TOGGLE-CYCLE
    gsettings set org.gnome.shell.extensions.dash-to-panel scroll-panel-action \
      NOTHING
    gsettings set org.gnome.shell.extensions.dash-to-panel scroll-icon-action \
      NOTHING
    gsettings set org.gnome.shell.extensions.dash-to-panel \
      panel-element-positions '{"0":[
        {"element":"showAppsButton","visible":true,"position":"stackedTL"},
        {"element":"activitiesButton","visible":false,"position":"stackedTL"},
        {"element":"leftBox","visible":true,"position":"stackedTL"},
        {"element":"taskbar","visible":true,"position":"stackedTL"},
        {"element":"dateMenu","visible":true,"position":"centerMonitor"},
        {"element":"centerBox","visible":true,"position":"stackedBR"},
        {"element":"rightBox","visible":true,"position":"stackedBR"},
        {"element":"systemMenu","visible":true,"position":"stackedBR"},
        {"element":"desktopButton","visible":true,"position":"stackedBR"}]}'

    # gnome software center
    gsettings set org.gnome.software download-updates false

    # file-chooser
    gsettings set org.gtk.Settings.FileChooser clock-format 24h
    gsettings set org.gtk.Settings.FileChooser sort-directories-first true

    # nautilus
    gsettings set org.gnome.nautilus.icon-view captions \
      "['size', 'none', 'none']"
    gsettings set org.gnome.nautilus.icon-view default-zoom-level small
    gsettings set org.gnome.nautilus.list-view default-zoom-level small
    gsettings set org.gnome.nautilus.list-view use-tree-view true
    gsettings set org.gnome.nautilus.preferences show-create-link true
    gsettings set org.gnome.nautilus.preferences show-delete-permanently true
    gsettings set org.gnome.nautilus.preferences thumbnail-limit 10

    # gnome-text-editor
    gsettings set org.gnome.TextEditor indent-style space
    gsettings set org.gnome.TextEditor highlight-current-line true
    gsettings set org.gnome.TextEditor show-line-numbers true
    gsettings set org.gnome.TextEditor show-right-margin true
    gsettings set org.gnome.TextEditor show-map true
    gsettings set org.gnome.TextEditor style-scheme classic-dark
    gsettings set org.gnome.TextEditor tab-width 2

    # gnome-console
    gsettings set org.gnome.Console audible-bell false
    gsettings set org.gnome.Console scrollback-lines 800000
    gsettings set org.gnome.Console transparency true

    # mutter
    gsettings set org.gnome.mutter attach-modal-dialogs false
    gsettings set org.gnome.mutter dynamic-workspaces false

    # plugins
    gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled \
      true
    gsettings set org.gnome.settings-daemon.plugins.power \
      sleep-inactive-ac-timeout 7200
    gsettings set org.gnome.settings-daemon.plugins.power \
      sleep-inactive-ac-type nothing
    gsettings set org.gnome.settings-daemon.plugins.media-keys calculator \
      "['<Super>c']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys control-center \
      "['<Super>s']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys home \
      "['<Super>f']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys www \
      "['<Super>w']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys \
      custom-keybindings "[
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/',
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/',
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/',
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/',
'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom0/ binding '<Super>e'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom0/ command gnome-text-editor
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom0/ name 'Open text editor'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom1/ binding '<Super>t'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom1/ command terminator
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom1/ name 'Open terminator'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom2/ binding '<Primary><Alt>t'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom2/ command terminator
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom2/ name 'Open terminator'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom3/ binding '<Shift><Super>c'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom3/ command gnome-characters
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom3/ name 'Open GNOME Characters'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom4/ binding '<Shift><Super>t'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom4/ command 'cool-retro-term --fullscreen'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.\
custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/\
custom-keybindings/custom4/ name 'Open Cool Retro Terminal'

  # Cinnamon
  elif [[ "${XDG_SESSION_DESKTOP@L}" =~ cinnamon ]]; then
    # cinnamon desktop
    gsettings set org.cinnamon enabled-applets "[
      'panel1:left:0:menu@cinnamon.org:0',
      'panel1:left:1:grouped-window-list@cinnamon.org:1',
      'panel1:right:0:workspace-switcher@cinnamon.org:2',
      'panel1:right:1:slideshow@cinnamon.org:3',
      'panel1:right:2:systray@cinnamon.org:4',
      'panel1:right:3:xapp-status@cinnamon.org:5',
      'panel1:right:4:notifications@cinnamon.org:6',
      'panel1:right:5:printers@cinnamon.org:7',
      'panel1:right:6:removable-drives@cinnamon.org:8',
      'panel1:right:7:keyboard@cinnamon.org:9',
      'panel1:right:8:favorites@cinnamon.org:10',
      'panel1:right:9:network@cinnamon.org:11',
      'panel1:right:10:sound@cinnamon.org:12',
      'panel1:right:11:power@cinnamon.org:13',
      'panel1:right:12:calendar@cinnamon.org:14',
      'panel1:right:13:cornerbar@cinnamon.org:15']"
    gsettings set org.cinnamon panel-zone-icon-sizes \
      '[{"panelId": 1, "left": 24, "center": 24, "right": 24}]'
    gsettings set org.cinnamon panel-zone-symbolic-icon-sizes \
      '[{"panelId": 1, "left": 20, "center": 20, "right": 20}]'
    gsettings set org.cinnamon panels-height "['1:30']"
    gsettings set org.cinnamon.theme name Matcha-dark-aliz
    gsettings set org.cinnamon.desktop.interface gtk-theme Matcha-dark-aliz
    gsettings set org.cinnamon.desktop.interface icon-theme BeautyLine
    gsettings set org.cinnamon.desktop.interface cursor-theme Breeze_Amber
    gsettings set org.x.apps.portal color-scheme prefer-dark
    gsettings set org.cinnamon.desktop.interface clock-show-date true
    gsettings set org.cinnamon.desktop.default-applications.terminal exec \
      terminator
    gsettings set org.cinnamon favorite-apps \
      "['nemo.desktop', 'terminator.desktop', 'cinnamon-settings.desktop']"
    gsettings set org.cinnamon.desktop.background.slideshow image-source \
      'directory:///usr/share/backgrounds/gdl'
    gsettings set org.cinnamon.desktop.background.slideshow random-order true
    gsettings set org.cinnamon.desktop.background.slideshow delay 10
    gsettings set org.cinnamon.desktop.background picture-uri \
      'file:///usr/share/backgrounds/gdl/gds-logo-dark-1920x1080.jpg'
    gsettings set org.cinnamon.desktop.background.slideshow slideshow-enabled \
      true
    xdg-user-dir PICTURES >> ~/.config/cinnamon/backgrounds/user-folders.lst
    gsettings set org.cinnamon workspace-osd-visible false
    gsettings set org.cinnamon workspace-expo-view-as-grid true

    # window manager
    gsettings set org.cinnamon.desktop.wm.preferences theme Matcha-dark-aliz
    gsettings set org.cinnamon.desktop.wm.preferences num-workspaces 2
    gsettings set org.cinnamon.desktop.wm.preferences action-scroll-titlebar \
      opacity
    gsettings set org.cinnamon.muffin workspaces-only-on-primary true

    # nemo
    gsettings set org.nemo.preferences date-format iso
    gsettings set org.nemo.preferences show-new-folder-icon-toolbar true
    gsettings set org.nemo.preferences show-open-in-terminal-toolbar true
    gsettings set org.nemo.preferences thumbnail-limit 10485760

    # mouse and touchpad
    gsettings set org.cinnamon.desktop.peripherals.mouse speed 1.0
    gsettings set org.cinnamon.desktop.peripherals.touchpad speed 1.0

    # keybindings
    gsettings set org.cinnamon.desktop.keybindings looking-glass-keybinding \
      "['<Primary><Shift><Alt>l']"
    gsettings set org.cinnamon.desktop.keybindings show-desklets \
      "['<Primary><Alt>d']"
    gsettings set org.cinnamon.desktop.keybindings.media-keys calculator \
      "['XF86Calculator', '<Super>c']"
    gsettings set org.cinnamon.desktop.keybindings.media-keys home \
      "['<Super>f', 'XF86Explorer']"
    gsettings set org.cinnamon.desktop.keybindings.media-keys screensaver \
      "['<Primary><Alt>l', 'XF86ScreenSaver', '<Super>l']"
    gsettings set org.cinnamon.desktop.keybindings.media-keys terminal \
      "['<Primary><Alt>t', '<Super>t']"
    gsettings set org.cinnamon.desktop.keybindings.media-keys www \
      "['XF86WWW', '<Super>w']"
    gsettings set org.cinnamon.desktop.keybindings.wm decrease-opacity \
      "['<Shift>MonBrightnessDown']"
    gsettings set org.cinnamon.desktop.keybindings.wm increase-opacity \
      "['<Shift>MonBrightnessUp']"
    gsettings set org.cinnamon.desktop.keybindings.wm push-tile-up \
      "['<Super>KP_Up']"
    gsettings set org.cinnamon.desktop.keybindings.wm push-tile-down \
      "['<Super>KP_Down']"
    gsettings set org.cinnamon.desktop.keybindings.wm push-tile-left \
      "['<Super>Left', '<Super>KP_Left']"
    gsettings set org.cinnamon.desktop.keybindings.wm push-tile-right \
      "['<Super>Right', '<Super>KP_Right']"
    gsettings set org.cinnamon.desktop.keybindings.wm toggle-maximized \
      "['<Super>Up']"
    gsettings set org.cinnamon.desktop.keybindings.wm minimize "['<Super>Down']"
    gsettings set org.cinnamon.desktop.keybindings.wm move-to-corner-ne \
      "['<Super>KP_Page_Up']"
    gsettings set org.cinnamon.desktop.keybindings.wm move-to-corner-nw \
      "['<Super>KP_Home']"
    gsettings set org.cinnamon.desktop.keybindings.wm move-to-corner-se \
      "['<Super>KP_Next']"
    gsettings set org.cinnamon.desktop.keybindings.wm move-to-corner-sw \
      "['<Super>KP_End']"
    gsettings set org.cinnamon.desktop.keybindings.wm move-to-center \
      "['<Super>KP_Begin']"
    gsettings set org.cinnamon.desktop.keybindings custom-list \
      "['custom0', 'custom1', 'custom2', 'custom3', 'custom4']"
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom0/ name 'System Settings'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom0/ command \
      cinnamon-settings
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom0/ binding "['<Super>s']"
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom1/ name 'Text Editor'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom1/ command xed
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom1/ binding "['<Super>e']"
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom2/ name \
      'Cool Retro Terminal'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom2/ command \
      'cool-retro-term --fullscreen'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom2/ binding \
      "['<Shift><Super>t']"
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom3/ name 'GNOME Characters'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom3/ command \
      gnome-characters
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom3/ binding \
      "['<Shift><Super>c']"
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom4/ name 'Kill Window'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom4/ command xkill
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/\
cinnamon/desktop/keybindings/custom-keybindings/custom4/ binding "['<Super>k']"

    # xed
    gsettings set org.x.editor.plugins active-plugins "['textsize', 'spell',
      'sort', 'joinlines', 'time', 'open-uri-context-menu', 'filebrowser',
      'docinfo', 'modelines', 'trailsave', 'bracketcompletion']"
    gsettings set org.x.editor.preferences.editor auto-close true
    gsettings set org.x.editor.preferences.editor auto-indent true
    gsettings set org.x.editor.preferences.editor bracket-matching true
    gsettings set org.x.editor.preferences.editor display-line-numbers true
    gsettings set org.x.editor.preferences.editor display-right-margin true
    gsettings set org.x.editor.preferences.editor highlight-current-line true
    gsettings set org.x.editor.preferences.editor prefer-dark-theme true
    gsettings set org.x.editor.preferences.editor right-margin-position 80
    gsettings set org.x.editor.preferences.editor scheme cobalt
    gsettings set org.x.editor.preferences.editor tabs-size 2
    gsettings set org.x.editor.preferences.ui minimap-visible true
    gsettings set org.x.editor.preferences.ui toolbar-visible false

    # keyboard
    gsettings set org.gnome.libgnomekbd.keyboard options \
      "['compat\tnumpad:microsoft']"

    # screensaver
    gsettings set org.cinnamon.desktop.screensaver lock-delay 2
    gsettings set org.cinnamon.desktop.screensaver show-album-art false
    gsettings set org.cinnamon.desktop.screensaver use-custom-format true
    gsettings set org.cinnamon.desktop.screensaver date-format '%A, %B %-e'
    gsettings set org.cinnamon.desktop.session idle-delay 600

    # power
    gsettings set org.cinnamon.settings-daemon.plugins.power idle-brightness 5
    gsettings set org.cinnamon.settings-daemon.plugins.power idle-dim-time 60
    gsettings set org.cinnamon.settings-daemon.plugins.power lock-on-suspend \
      true
    gsettings set org.cinnamon.settings-daemon.plugins.power \
      sleep-display-battery 300
    gsettings set org.cinnamon.settings-daemon.plugins.power \
      sleep-inactive-battery-timeout 1800

  # Xfce
  elif [[ "${XDG_SESSION_DESKTOP@L}" =~ xfce ]]; then
    gsettings set org.gtk.Settings.FileChooser sort-directories-first true
    gsettings set org.xfce.mousepad.preferences.file add-last-end-of-line true
    gsettings set org.xfce.mousepad.preferences.view auto-indent true
    gsettings set org.xfce.mousepad.preferences.view color-scheme cobalt
    gsettings set org.xfce.mousepad.preferences.view highlight-current-line true
    gsettings set org.xfce.mousepad.preferences.view insert-spaces true
    gsettings set org.xfce.mousepad.preferences.view match-braces true
    gsettings set org.xfce.mousepad.preferences.view show-line-numbers true
    gsettings set org.xfce.mousepad.preferences.view show-right-margin true
    gsettings set org.xfce.mousepad.preferences.view tab-width 2
    gsettings set org.xfce.mousepad.preferences.view word-wrap true
    gsettings set org.xfce.mousepad.preferences.window statusbar-visible true
  fi
}

main

# self-destruct
rm ~/.config/gdl-config-script
