#!/bin/bash
#
# Golden Drake Linux (GDL) desktop environment customization script, for user
# settings that are best changed through a command rather than a config file.
# This script will run once, at user's first login, then self-destruct.

case "${XDG_SESSION_DESKTOP}" in
  KDE)

    # plasma theme
    if [[ -d /usr/share/plasma/look-and-feel/com.gitlab.cscs.matchama ]]; then
      plasma-apply-lookandfeel -a com.gitlab.cscs.matchama-dark
      plasma-apply-desktoptheme Matchama-Adaptive-Colors
      plasma-apply-colorscheme MatchamaDarkAliz
    else
      plasma-apply-lookandfeel -a org.kde.breezedark.desktop
      plasma-apply-desktoptheme breeze-dark
      plasma-apply-colorscheme BreezeDark
    fi
    plasma-apply-cursortheme Breeze_Amber
    /usr/lib/plasma-changeicons BeautyLine
    kwriteconfig5 --file kdeglobals --group KDE --key SingleClick false
    ;;

  gnome)

    # gnome desktop
    gsettings set org.gnome.desktop.background picture-uri \
      'file:///usr/share/backgrounds/archlinux/gds-logo-dark-1920x1080.jpg'
    gsettings set org.gnome.desktop.input-sources xkb-options \
      "['numpad:microsoft']"
    gsettings set org.gnome.desktop.interface clock-show-weekday true
    gsettings set org.gnome.desktop.interface cursor-theme 'Breeze_Amber'
    gsettings set org.gnome.desktop.interface gtk-theme 'Matcha-dark-aliz'
    gsettings set org.gnome.desktop.interface icon-theme 'Surfn-Numix'
    gsettings set org.gnome.desktop.interface show-battery-percentage true
    gsettings set org.gnome.desktop.notifications show-in-lock-screen false
    gsettings set org.gnome.desktop.peripherals.mouse speed 1.0
    gsettings set org.gnome.desktop.screensaver picture-uri \
      'file:///usr/share/backgrounds/archlinux/gds-logo-dark-1920x1080.jpg'
    gsettings set org.gnome.desktop.session idle-delay 'uint32 600'
    gsettings set org.gnome.desktop.wm.keybindings panel-run-dialog \
      "['<Super>r']"
    gsettings set org.gnome.desktop.wm.keybindings show-desktop "['<Super>d']"
    gsettings set org.gnome.desktop.wm.preferences button-layout \
      'appmenu:minimize,maximize,close'

    # gnome shell
    gsettings set org.gnome.shell enabled-extensions "[
      'user-theme@gnome-shell-extensions.gcampax.github.com',
      'launch-new-instance@gnome-shell-extensions.gcampax.github.com',
      'windowsNavigator@gnome-shell-extensions.gcampax.github.com',
      'apps-menu@gnome-shell-extensions.gcampax.github.com',
      'places-menu@gnome-shell-extensions.gcampax.github.com',
      'workspace-indicator@gnome-shell-extensions.gcampax.github.com',
      'drive-menu@gnome-shell-extensions.gcampax.github.com',
      'clipboard-indicator@tudmotu.com',
      'appindicatorsupport@rgcjonas.gmail.com'
    ]"
    gsettings set org.gnome.shell.extensions.user-theme name 'Matcha-dark-aliz'
    gsettings set org.gnome.shell.keybindings toggle-overview '@as []'

    # gnome software center
    gsettings set org.gnome.software download-updates false

    # plugins
    gsettings set org.gnome.settings-daemon.plugins.color \
      night-light-enabled true
    gsettings set org.gnome.settings-daemon.plugins.power \
      sleep-inactive-ac-timeout 7200
    gsettings set org.gnome.settings-daemon.plugins.media-keys calculator \
      "['<Super>c']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys control-center \
      "['<Super>s']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys home \
      "['<Super>f']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys www \
      "['<Super>w']"
    gsettings set org.gnome.settings-daemon.plugins.media-keys \
      custom-keybindings "[
    '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/',
    '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/',
    '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/',
    '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/',
    '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/',
    '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/'
    ]"
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding '<Super>e'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command 'gedit'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name 'Open text editor'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ binding '<Super>t'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command 'terminator'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name 'Open terminator'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ binding '<Primary><Alt>t'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ command 'terminator'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/ name 'Open terminator'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ binding '<Shift><Super>c'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ command 'gnome-characters'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom3/ name 'Open GNOME Characters'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ binding '<Shift><Super>t'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ command 'cool-retro-term --fullscreen'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom4/ name 'Open Cool Retro Terminal'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ binding '<Shift><Primary><Alt>t'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ command 'cool-retro-term --fullscreen'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom5/ name 'Open Cool Retro Terminal'

    # mutter
    gsettings set org.gnome.mutter attach-modal-dialogs false

    # nautilus
    gsettings set org.gnome.nautilus.icon-view captions \
      "['size', 'none', 'none']"
    gsettings set org.gnome.nautilus.icon-view default-zoom-level 'small'
    gsettings set org.gnome.nautilus.list-view default-zoom-level 'small'
    gsettings set org.gnome.nautilus.list-view use-tree-view true
    gsettings set org.gnome.nautilus.preferences default-folder-viewer \
      'list-view'
    gsettings set org.gnome.nautilus.preferences show-delete-permanently true
    gsettings set org.gnome.nautilus.preferences thumbnail-limit 'uint64 100'

    # gedit
    gsettings set org.gnome.gedit.plugins active-plugins "['spell', 'sort',
      'docinfo', 'filebrowser', 'modelines', 'quickhighlight']"
    gsettings set org.gnome.gedit.preferences.editor display-right-margin true
    gsettings set org.gnome.gedit.preferences.editor insert-spaces true
    gsettings set org.gnome.gedit.preferences.editor scheme 'cobalt'
    gsettings set org.gnome.gedit.preferences.editor tabs-size 'uint32 2'
    gsettings set org.gnome.gedit.preferences.editor wrap-last-split-mode 'word'

    # file-chooser
    gsettings set org.gtk.Settings.FileChooser sort-directories-first true

    # wallpaper slideshow
    variety --resume
    ;;

  cinnamon)

    # gnome software center
    gsettings set org.gnome.software download-updates false

    # cinnamon desktop
    gsettings set org.cinnamon enabled-applets "[
      'panel1:left:0:menu@cinnamon.org:0',
      'panel1:left:1:grouped-window-list@cinnamon.org:1',
      'panel1:right:0:SpicesUpdate@claudiux:2',
      'panel1:right:1:temperature@fevimu:3',
      'panel1:right:2:workspace-switcher@cinnamon.org:4',
      'panel1:right:3:slideshow@cinnamon.org:5',
      'panel1:right:4:favorites@cinnamon.org:6',
      'panel1:right:5:color-picker@fmete:7',
      'panel1:right:6:removable-drives@cinnamon.org:8',
      'panel1:right:7:printers@cinnamon.org:9',
      'panel1:right:8:systray@cinnamon.org:10',
      'panel1:right:9:xapp-status@cinnamon.org:11',
      'panel1:right:10:keyboard@cinnamon.org:12',
      'panel1:right:11:network@cinnamon.org:13',
      'panel1:right:12:power@cinnamon.org:14',
      'panel1:right:13:sound@cinnamon.org:15',
      'panel1:right:14:calendar@simonwiles.net:16',
      'panel1:right:15:notifications@cinnamon.org:17',
      'panel1:right:16:show-desktop@cinnamon.org:18'
    ]"
    gsettings set org.cinnamon favorite-apps "[
      'nemo.desktop',
      'terminator.desktop',
      'org.gnome.Software.desktop',
      'cinnamon-settings.desktop'
    ]"
    gsettings set org.cinnamon panel-zone-icon-sizes \
      '[{"panelId": 1, "left": 24, "center": 24, "right": 24}]"'
    gsettings set org.cinnamon panel-zone-symbolic-icon-sizes \
      '[{"panelId": 1, "left": 20, "center": 20, "right": 20}]"'
    gsettings set org.cinnamon panels-height "['1:30']"
    gsettings set org.cinnamon workspace-expo-view-as-grid true
    gsettings set org.cinnamon workspace-osd-visible false
    gsettings set org.cinnamon.SessionManager quit-time-delay 60
    gsettings set org.cinnamon.theme name 'Matcha-dark-aliz'
    gsettings set org.cinnamon.desktop.default-applications.calculator exec \
      'gnome-calculator'
    gsettings set org.cinnamon.desktop.default-applications.terminal exec \
      'terminator'
    gsettings set org.cinnamon.desktop.interface clock-show-date true
    gsettings set org.cinnamon.desktop.interface cursor-theme 'Breeze_Amber'
    gsettings set org.cinnamon.desktop.interface gtk-theme 'Matcha-dark-aliz'
    gsettings set org.cinnamon.desktop.interface icon-theme 'Surfn-Numix'
    gsettings set org.cinnamon.desktop.background.slideshow image-source \
      'directory:///usr/share/backgrounds/archlinux'
    gsettings set org.cinnamon.desktop.background.slideshow random-order true
    gsettings set org.cinnamon.desktop.background.slideshow delay 1
    gsettings set org.cinnamon.desktop.background picture-uri \
      'file:///usr/share/backgrounds/archlinux/gds-logo-dark-1920x1080.jpg'
    sleep 30 && gsettings set org.cinnamon.desktop.background.slideshow \
      slideshow-enabled true &

    # keybindings
    gsettings set org.cinnamon.desktop.keybindings looking-glass-keybinding \
      "['<Primary><Shift><Alt>l']"
    gsettings set org.cinnamon.desktop.keybindings show-desklets \
      "['<Primary><Shift><Alt>d']"
    gsettings set org.cinnamon.desktop.keybindings.media-keys calculator \
      "['XF86Calculator', '<Super>c', '<Primary><Alt>c']"
    gsettings set org.cinnamon.desktop.keybindings.media-keys home \
      "['<Super>f', 'XF86Explorer', '<Primary><Alt>f']"
    gsettings set org.cinnamon.desktop.keybindings.media-keys screensaver \
      "['<Control><Alt>l', 'XF86ScreenSaver', '<Super>l']"
    gsettings set org.cinnamon.desktop.keybindings.media-keys terminal \
      "['<Primary><Alt>t', '<Super>t', '<Super>Return']"
    gsettings set org.cinnamon.desktop.keybindings.media-keys www \
      "['XF86WWW', '<Super>w', '<Primary><Alt>w']"
    gsettings set org.cinnamon.desktop.keybindings.wm decrease-opacity \
      "['<Shift>MonBrightnessDown']"
    gsettings set org.cinnamon.desktop.keybindings.wm increase-opacity \
      "['<Shift>MonBrightnessUp']"
    gsettings set org.cinnamon.desktop.keybindings.wm push-tile-down "[]"
    gsettings set org.cinnamon.desktop.keybindings.wm push-tile-up "[]"
    gsettings set org.cinnamon.desktop.keybindings.wm maximize "['<Super>Up']"
    gsettings set org.cinnamon.desktop.keybindings.wm minimize \
      "['<Super>h', '<Primary><Alt>h']"
    gsettings set org.cinnamon.desktop.keybindings.wm panel-run-dialog \
      "['<Alt>F2', '<Super>r', '<Primary><Alt>r']"
    gsettings set org.cinnamon.desktop.keybindings.wm show-desktop \
      "['<Super>d', '<Primary><Alt>d']"
    gsettings set org.cinnamon.desktop.keybindings.wm unmaximize \
      "['<Alt>F5', '<Super>Down']"
    gsettings set org.cinnamon.desktop.keybindings custom-list \
      "['custom0', 'custom1', 'custom2', 'custom3', 'custom4']"
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ binding "['<Super>s', '<Primary><Alt>s']"
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ command 'cinnamon-settings'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom0/ name 'System Settings'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ binding "['<Super>e', '<Primary><Alt>e']"
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ command 'xed'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom1/ name 'Text Editor'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ binding "['<Shift><Super>t', '<Primary><Shift><Alt>t', '<Shift><Super>Return']"
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ command 'cool-retro-term --fullscreen'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom2/ name 'Cool Retro Terminal'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom3/ binding "['<Shift><Super>c', '<Primary><Shift><Alt>c']"
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom3/ command 'gnome-characters'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom3/ name 'GNOME Characters'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom4/ binding "['<Super>k', '<Primary><Alt>k']"
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom4/ command 'xkill'
    gsettings set org.cinnamon.desktop.keybindings.custom-keybinding:/org/cinnamon/desktop/keybindings/custom-keybindings/custom4/ name 'Kill Window'

    # screensaver
    gsettings set org.cinnamon.desktop.screensaver lock-delay 'uint32 2'
    gsettings set org.cinnamon.desktop.screensaver show-album-art false
    gsettings set org.cinnamon.desktop.screensaver use-custom-format true
    gsettings set org.cinnamon.desktop.screensaver date-format '%A, %B %-e'
    gsettings set org.cinnamon.desktop.session idle-delay 'uint32 600'

    # window manager
    gsettings set org.cinnamon.desktop.wm.preferences action-scroll-titlebar \
      'opacity'
    gsettings set org.cinnamon.desktop.wm.preferences min-window-opacity 10
    gsettings set org.cinnamon.desktop.wm.preferences num-workspaces 4
    gsettings set org.cinnamon.desktop.wm.preferences theme 'Matcha-dark-aliz'
    gsettings set org.cinnamon.muffin placement-mode 'automatic'
    gsettings set org.cinnamon.muffin workspaces-only-on-primary true

    # mouse
    gsettings set org.cinnamon.settings-daemon.peripherals.mouse \
      custom-acceleration true
    gsettings set org.cinnamon.settings-daemon.peripherals.mouse \
      custom-threshold true
    gsettings set org.cinnamon.settings-daemon.peripherals.mouse \
      motion-acceleration 10.0
    gsettings set org.cinnamon.settings-daemon.peripherals.mouse \
      motion-threshold 1

    # touchpad
    gsettings set org.cinnamon.settings-daemon.peripherals.touchpad \
      custom-acceleration true
    gsettings set org.cinnamon.settings-daemon.peripherals.touchpad \
      custom-threshold true
    gsettings set org.cinnamon.settings-daemon.peripherals.touchpad \
      disable-with-external-mouse true
    gsettings set org.cinnamon.settings-daemon.peripherals.touchpad \
      horizontal-scrolling true
    gsettings set org.cinnamon.settings-daemon.peripherals.touchpad \
      motion-acceleration 10.0
    gsettings set org.cinnamon.settings-daemon.peripherals.touchpad \
      motion-threshold 1
    gsettings set org.cinnamon.settings-daemon.peripherals.touchpad \
      scrolling-method 1
    gsettings set org.cinnamon.settings-daemon.peripherals.touchpad \
      touchpad-enabled true

    # power
    gsettings set org.cinnamon.settings-daemon.plugins.power \
      button-power 'interactive'
    gsettings set org.cinnamon.settings-daemon.plugins.power idle-brightness 5
    gsettings set org.cinnamon.settings-daemon.plugins.power idle-dim-time 60
    gsettings set org.cinnamon.settings-daemon.plugins.power \
      lid-close-ac-action 'suspend'
    gsettings set org.cinnamon.settings-daemon.plugins.power \
      lid-close-battery-action 'suspend'
    gsettings set org.cinnamon.settings-daemon.plugins.power \
      lock-on-suspend true
    gsettings set org.cinnamon.settings-daemon.plugins.power \
      sleep-display-ac 3600
    gsettings set org.cinnamon.settings-daemon.plugins.power \
      sleep-display-battery 300
    gsettings set org.cinnamon.settings-daemon.plugins.power \
      sleep-inactive-ac-timeout 0
    gsettings set org.cinnamon.settings-daemon.plugins.power \
      sleep-inactive-battery-timeout 1800

    # keyboard
    gsettings set org.gnome.libgnomekbd.keyboard options \
      "['compat\tnumpad:microsoft']"

    # file-chooser
    gsettings set org.gtk.Settings.FileChooser sort-directories-first true

    # nemo
    gsettings set org.nemo.preferences date-format 'iso'
    gsettings set org.nemo.preferences default-folder-viewer 'list-view'
    gsettings set org.nemo.preferences executable-text-activation 'display'
    gsettings set org.nemo.preferences show-full-path-titles true
    gsettings set org.nemo.preferences show-new-folder-icon-toolbar true
    gsettings set org.nemo.preferences show-open-in-terminal-toolbar true
    gsettings set org.nemo.preferences thumbnail-limit 'uint64 104857600'

    # xed
    gsettings set org.x.editor.plugins active-plugins "['textsize', 'spell',
      'sort', 'joinlines', 'time', 'open-uri-context-menu', 'filebrowser',
      'docinfo', 'modelines', 'trailsave']"
    gsettings set org.x.editor.preferences.editor auto-indent true
    gsettings set org.x.editor.preferences.editor bracket-matching true
    gsettings set org.x.editor.preferences.editor display-line-numbers true
    gsettings set org.x.editor.preferences.editor display-right-margin true
    gsettings set org.x.editor.preferences.editor highlight-current-line true
    gsettings set org.x.editor.preferences.editor prefer-dark-theme true
    gsettings set org.x.editor.preferences.editor right-margin-position \
      'uint32 80'
    gsettings set org.x.editor.preferences.editor scheme 'cobalt'
    gsettings set org.x.editor.preferences.editor tabs-size 'uint32 2'
    gsettings set org.x.editor.preferences.ui minimap-visible true
    gsettings set org.x.editor.preferences.ui toolbar-visible false
    ;;

  xfce)

    # gnome software center
    gsettings set org.gnome.software download-updates false

    # file-chooser
    gsettings set org.gtk.Settings.FileChooser sort-directories-first true

    # mousepad
    gsettings set org.xfce.mousepad.preferences.file add-last-end-of-line true
    gsettings set org.xfce.mousepad.preferences.view auto-indent true
    gsettings set org.xfce.mousepad.preferences.view color-scheme cobalt
    gsettings set org.xfce.mousepad.preferences.view highlight-current-line true
    gsettings set org.xfce.mousepad.preferences.view insert-spaces true
    gsettings set org.xfce.mousepad.preferences.view match-braces true
    gsettings set org.xfce.mousepad.preferences.view show-line-numbers true
    gsettings set org.xfce.mousepad.preferences.view show-right-margin true
    gsettings set org.xfce.mousepad.preferences.view tab-width 2
    gsettings set org.xfce.mousepad.preferences.view word-wrap true
    gsettings set org.xfce.mousepad.preferences.window statusbar-visible true
    ;;
esac

# language input
function add_input_source {
  local input_sources
  input_sources="$(gsettings get org.gnome.desktop.input-sources sources)"
  if [[ -n "$1" ]] && grep -vq "$1" <<<"${input_sources}"; then
    gsettings set org.gnome.desktop.input-sources sources \
      "${input_sources/]}, $1]"
  fi
}
function add_input_engine {
  local input_engines
  input_engines="$(gsettings get \
    org.freedesktop.ibus.general preload-engines)"
  if [[ -n "$1" ]] && grep -vq "$1" <<<"${input_engines}"; then
    gsettings set org.freedesktop.ibus.general preload-engines \
      "${input_engines/]}, '$1']"
  fi
}
if pacman -Q 'ibus'; then
  case "${XDG_SESSION_DESKTOP}" in
    gnome)
      gsettings set org.gnome.desktop.interface.gtk-im-module 'ibus'
      pacman -Q 'ibus-libpinyin' && add_input_source "('ibus', 'libpinyin')"
      pacman -Q 'ibus-chewing' && add_input_source "('ibus', 'chewing')"
      pacman -Q 'ibus-kkc' && add_input_source "('ibus', 'kkc')"
      pacman -Q 'ibus-hangul' && add_input_source "('ibus', 'hangul')"
      ;;
    *)
      pacman -Q 'ibus-libpinyin' && add_input_engine 'libpinyin'
      pacman -Q 'ibus-chewing' && add_input_engine 'chewing'
      pacman -Q 'ibus-kkc' && add_input_engine 'kkc'
      pacman -Q 'ibus-hangul' && add_input_engine 'hangul'
      ;;
  esac
  gsettings set org.freedesktop.ibus.general.hotkey triggers \
    "['<Super>space', '<Control>space']"
fi

# cleanup
rm ~/.config/autostart/gdl-config-script.desktop
rm ~/.config/gdl-config-script
