#!/bin/bash
#
# This script will run once, at user's first login, then self-destruct.

# file-chooser
gsettings set org.gtk.Settings.FileChooser sort-directories-first true

# mousepad
gsettings set org.xfce.mousepad.preferences.file add-last-end-of-line true
gsettings set org.xfce.mousepad.preferences.view auto-indent true
gsettings set org.xfce.mousepad.preferences.view color-scheme cobalt
gsettings set org.xfce.mousepad.preferences.view highlight-current-line true
gsettings set org.xfce.mousepad.preferences.view insert-spaces true
gsettings set org.xfce.mousepad.preferences.view match-braces true
gsettings set org.xfce.mousepad.preferences.view show-line-numbers true
gsettings set org.xfce.mousepad.preferences.view show-right-margin true
gsettings set org.xfce.mousepad.preferences.view tab-width 2
gsettings set org.xfce.mousepad.preferences.view word-wrap true
gsettings set org.xfce.mousepad.preferences.window statusbar-visible true

# cleanup
rm ~/.config/autostart/set-initial-gsettings.desktop
rm ~/.config/set-initial-gsettings
